name: Generate Snake Game

on:
  schedule: # Run at midnight UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to run the workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository content
      - name: Checkout repository content
        uses: actions/checkout@v3

      # Generate the snake game from your GitHub user contributions graph
      - name: Generate Snake Game from GitHub contributions graph
        uses: Platane/snk@v2
        with:
          github_user_name: MarcAusss
          outputs: dist

      # Push the generated SVG to the `output` branch
      - name: Push generated SVG to the `main` branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
