name: Generate Snake Game

on:
  schedule: # Run at 5 AM UTC every day
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Generate Snake Game from GitHub contributions graph
        uses: Platane/snk@v2
        with:
          github_user_name: MarcAusss
          output: dist/github-snake.svg

      - name: Push the generated Snake Game to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
